"""
Seed data for the Skill DNA Map (Phase 3, Stage 1): DSA topics ("nodes"), the
prerequisite edges between them, and canonical problems with verified test cases.

What "verified" means here:
- Every problem is a standard, well-known one (Two Sum, Valid Parentheses, ...).
- Test cases are the worked examples printed in each problem's own statement.
  None were generated by an LLM and none were hand-invented. Extra edge cases
  were deliberately NOT added; a thin set of cases is a known limit for Stage 2.
- scripts/verify_dsa_seed.py runs an independent reference solution over every
  case and fails if any expected_output disagrees, and checks the graph is a DAG.
  Re-run it after editing anything in this file.

Test-case format (DSAProblem.test_cases):
    {"input": {<parameter name>: <value>, ...}, "expected_output": <value>}
Parameter names follow each problem's usual signature. Encoding conventions,
so Stage 2's code-execution harness has one rule per type:
- Linked list: a plain array of node values, in order ([] = empty list).
- Binary tree: level-order array, null for a missing child ([3,9,20,null,null,15,7]).
- In-place problems (Merge Sorted Array): expected_output is the array afterwards.
- Return values are compared exactly; where a statement allows several valid
  answers (Two Sum's "any order"), the description pins one ("ascending order").

Problem descriptions are written in our own words: the technical contract only.
The career-flavoured story is added separately (problem_framing.py) and is
always shown next to, never instead of, this text.
"""

# Career path names must match app/pipeline/career_path_registry.CAREER_PATHS
# exactly. AIML, DATA, CLOUD and UIUX previously each covered a since-split
# pair; every node that referenced one of those now references BOTH of that
# pair's new constants (see docs/PROJECT_BIOGRAPHY.md's "Career Path
# Restructuring" entry) - a judgement call, not a re-derivation, since which
# half of a split each topic "really" belongs to isn't something this
# mechanical translation can know. RESEARCH is gone: "Research / Advanced
# Computing" was removed entirely, so it no longer appears on any node.
FULL_STACK = "Full-Stack Development"
AI_ENG = "AI Engineering"
ML_ENG = "Machine Learning Engineering"
DATA_SCI = "Data Science"
DATA_ANALYTICS = "Data Analytics"
CYBER = "Cybersecurity"
CLOUD_ENG = "Cloud Engineering"
DEVOPS = "DevOps"
MOBILE = "Mobile App Development"
GAME = "Game Development"
UIUX_DESIGN = "UI/UX Design"
FRONTEND = "Frontend Development"
BACKEND = "Backend Engineering"

# XP per problem, from the master doc's gamification table.
POINTS_BY_DIFFICULTY = {"Easy": 10, "Medium": 25, "Hard": 50}

# topic -> its prerequisites (topic names, resolved to IDs at seed time) and the
# career paths it is especially critical for. career_paths is a judgement call
# about where each topic is used day to day; it only drives highlighting on the
# map, never locking. Unlisted paths still see the node, just not highlighted.
NODES = [
    {"topic": "Arrays", "difficulty": "Easy", "prerequisites": [],
     "career_paths": [AI_ENG, ML_ENG, DATA_SCI, DATA_ANALYTICS, GAME]},
    {"topic": "Strings", "difficulty": "Easy", "prerequisites": ["Arrays"],
     "career_paths": [FULL_STACK, CYBER, BACKEND]},
    {"topic": "Hash Maps & Sets", "difficulty": "Easy", "prerequisites": ["Arrays"],
     "career_paths": [FULL_STACK, BACKEND, CYBER, DATA_SCI, DATA_ANALYTICS, CLOUD_ENG, DEVOPS]},
    {"topic": "Two Pointers", "difficulty": "Easy", "prerequisites": ["Arrays"],
     "career_paths": [DATA_SCI, DATA_ANALYTICS, GAME]},
    {"topic": "Sorting", "difficulty": "Medium", "prerequisites": ["Arrays"],
     "career_paths": [FULL_STACK, DATA_SCI, DATA_ANALYTICS, BACKEND]},
    {"topic": "Binary Search", "difficulty": "Easy", "prerequisites": ["Sorting"],
     "career_paths": [FULL_STACK, BACKEND, CLOUD_ENG, DEVOPS]},
    {"topic": "Sliding Window", "difficulty": "Medium", "prerequisites": ["Two Pointers", "Hash Maps & Sets"],
     "career_paths": [BACKEND, CLOUD_ENG, DEVOPS, CYBER, DATA_SCI, DATA_ANALYTICS]},
    {"topic": "Stacks & Queues", "difficulty": "Easy", "prerequisites": ["Arrays"],
     "career_paths": [BACKEND, CLOUD_ENG, DEVOPS, MOBILE, UIUX_DESIGN, FRONTEND]},
    {"topic": "Linked Lists", "difficulty": "Easy", "prerequisites": ["Arrays"],
     "career_paths": [BACKEND, GAME]},
    {"topic": "Recursion", "difficulty": "Easy", "prerequisites": ["Stacks & Queues"],
     "career_paths": [AI_ENG, ML_ENG, UIUX_DESIGN, FRONTEND, GAME]},
    {"topic": "Trees", "difficulty": "Medium", "prerequisites": ["Recursion", "Linked Lists"],
     "career_paths": [UIUX_DESIGN, FRONTEND, GAME, AI_ENG, ML_ENG, FULL_STACK, MOBILE]},
    {"topic": "Binary Search Trees", "difficulty": "Medium", "prerequisites": ["Trees", "Binary Search"],
     "career_paths": [BACKEND, FULL_STACK]},
    {"topic": "Heaps", "difficulty": "Medium", "prerequisites": ["Trees"],
     "career_paths": [AI_ENG, ML_ENG, DATA_SCI, DATA_ANALYTICS, CLOUD_ENG, DEVOPS, GAME]},
    {"topic": "Graphs", "difficulty": "Medium", "prerequisites": ["Trees"],
     "career_paths": [CYBER, CLOUD_ENG, DEVOPS, GAME, AI_ENG, ML_ENG]},
    {"topic": "Dynamic Programming", "difficulty": "Hard", "prerequisites": ["Recursion", "Hash Maps & Sets"],
     "career_paths": [AI_ENG, ML_ENG, DATA_SCI, DATA_ANALYTICS]},
]


def _case(input_, expected_output):
    return {"input": input_, "expected_output": expected_output}


PROBLEMS = [
    # ---------------------------------------------------------------- Arrays
    {"node": "Arrays", "title": "Best Time to Buy and Sell Stock", "difficulty": "Easy",
     "description": (
         "You are given prices, where prices[i] is a stock's price on day i. Choose one day to buy "
         "and a LATER day to sell. Return the maximum profit you can make, or 0 if no profit is possible."
     ),
     "test_cases": [
         _case({"prices": [7, 1, 5, 3, 6, 4]}, 5),
         _case({"prices": [7, 6, 4, 3, 1]}, 0),
     ]},
    {"node": "Arrays", "title": "Maximum Subarray", "difficulty": "Medium",
     "description": (
         "Given an integer array nums, find the contiguous non-empty subarray with the largest sum "
         "and return that sum."
     ),
     "test_cases": [
         _case({"nums": [-2, 1, -3, 4, -1, 2, 1, -5, 4]}, 6),
         _case({"nums": [1]}, 1),
         _case({"nums": [5, 4, -1, 7, 8]}, 23),
     ]},

    # --------------------------------------------------------------- Strings
    {"node": "Strings", "title": "Valid Anagram", "difficulty": "Easy",
     "description": (
         "Given two strings s and t, return true if t is an anagram of s (the same letters, each used "
         "the same number of times, in any order), otherwise false."
     ),
     "test_cases": [
         _case({"s": "anagram", "t": "nagaram"}, True),
         _case({"s": "rat", "t": "car"}, False),
     ]},
    {"node": "Strings", "title": "Longest Common Prefix", "difficulty": "Easy",
     "description": (
         "Given an array of strings strs, return the longest prefix that every string starts with. "
         "If there is none, return the empty string."
     ),
     "test_cases": [
         _case({"strs": ["flower", "flow", "flight"]}, "fl"),
         _case({"strs": ["dog", "racecar", "car"]}, ""),
     ]},

    # ------------------------------------------------------- Hash Maps & Sets
    {"node": "Hash Maps & Sets", "title": "Two Sum", "difficulty": "Easy",
     "description": (
         "Given an integer array nums and an integer target, return the indices of the two numbers "
         "that add up to target. Exactly one solution exists and you may not use the same element "
         "twice. Return the two indices in ascending order."
     ),
     "test_cases": [
         _case({"nums": [2, 7, 11, 15], "target": 9}, [0, 1]),
         _case({"nums": [3, 2, 4], "target": 6}, [1, 2]),
         _case({"nums": [3, 3], "target": 6}, [0, 1]),
     ]},
    {"node": "Hash Maps & Sets", "title": "Contains Duplicate", "difficulty": "Easy",
     "description": (
         "Given an integer array nums, return true if any value appears at least twice, and false "
         "if every element is distinct."
     ),
     "test_cases": [
         _case({"nums": [1, 2, 3, 1]}, True),
         _case({"nums": [1, 2, 3, 4]}, False),
         _case({"nums": [1, 1, 1, 3, 3, 4, 3, 2, 4, 2]}, True),
     ]},

    # ---------------------------------------------------------- Two Pointers
    {"node": "Two Pointers", "title": "Valid Palindrome", "difficulty": "Easy",
     "description": (
         "A phrase is a palindrome if, after lower-casing it and removing every character that is not "
         "a letter or digit, it reads the same forwards and backwards. Given a string s, return true "
         "if it is a palindrome, otherwise false."
     ),
     "test_cases": [
         _case({"s": "A man, a plan, a canal: Panama"}, True),
         _case({"s": "race a car"}, False),
         _case({"s": " "}, True),
     ]},
    {"node": "Two Pointers", "title": "Container With Most Water", "difficulty": "Medium",
     "description": (
         "height[i] is the height of a vertical line drawn at position i. Pick two lines; together "
         "with the x-axis they form a container, and its water is (distance between the lines) x "
         "(the shorter line's height). Return the maximum amount of water a container can hold."
     ),
     "test_cases": [
         _case({"height": [1, 8, 6, 2, 5, 4, 8, 3, 7]}, 49),
         _case({"height": [1, 1]}, 1),
     ]},

    # --------------------------------------------------------------- Sorting
    {"node": "Sorting", "title": "Merge Sorted Array", "difficulty": "Easy",
     "description": (
         "nums1 holds m sorted values followed by n zeros of spare room; nums2 holds n sorted values. "
         "Merge nums2 into nums1 so that nums1 contains all m+n values in sorted order. "
         "The expected output is nums1 after merging."
     ),
     "test_cases": [
         _case({"nums1": [1, 2, 3, 0, 0, 0], "m": 3, "nums2": [2, 5, 6], "n": 3}, [1, 2, 2, 3, 5, 6]),
         _case({"nums1": [1], "m": 1, "nums2": [], "n": 0}, [1]),
         _case({"nums1": [0], "m": 0, "nums2": [1], "n": 1}, [1]),
     ]},
    {"node": "Sorting", "title": "Merge Intervals", "difficulty": "Medium",
     "description": (
         "Given an array of intervals [start, end], merge every group of overlapping intervals "
         "(intervals that touch at an endpoint overlap) and return the merged, non-overlapping "
         "intervals sorted by start."
     ),
     "test_cases": [
         _case({"intervals": [[1, 3], [2, 6], [8, 10], [15, 18]]}, [[1, 6], [8, 10], [15, 18]]),
         _case({"intervals": [[1, 4], [4, 5]]}, [[1, 5]]),
         _case({"intervals": [[4, 7], [1, 4]]}, [[1, 7]]),
     ]},

    # --------------------------------------------------------- Binary Search
    {"node": "Binary Search", "title": "Binary Search", "difficulty": "Easy",
     "description": (
         "Given an array nums of distinct integers sorted in ascending order and an integer target, "
         "return the index of target in nums, or -1 if it is not there. Aim for O(log n) time."
     ),
     "test_cases": [
         _case({"nums": [-1, 0, 3, 5, 9, 12], "target": 9}, 4),
         _case({"nums": [-1, 0, 3, 5, 9, 12], "target": 2}, -1),
     ]},
    {"node": "Binary Search", "title": "Search Insert Position", "difficulty": "Easy",
     "description": (
         "Given a sorted array nums of distinct integers and a target, return the index of target if "
         "it is present; otherwise return the index where it would have to be inserted to keep the "
         "array sorted. Aim for O(log n) time."
     ),
     "test_cases": [
         _case({"nums": [1, 3, 5, 6], "target": 5}, 2),
         _case({"nums": [1, 3, 5, 6], "target": 2}, 1),
         _case({"nums": [1, 3, 5, 6], "target": 7}, 4),
     ]},

    # -------------------------------------------------------- Sliding Window
    {"node": "Sliding Window", "title": "Longest Substring Without Repeating Characters", "difficulty": "Medium",
     "description": (
         "Given a string s, return the length of the longest substring that contains no repeated "
         "character."
     ),
     "test_cases": [
         _case({"s": "abcabcbb"}, 3),
         _case({"s": "bbbbb"}, 1),
         _case({"s": "pwwkew"}, 3),
     ]},
    {"node": "Sliding Window", "title": "Minimum Size Subarray Sum", "difficulty": "Medium",
     "description": (
         "Given an array of positive integers nums and a positive integer target, return the length "
         "of the shortest contiguous subarray whose sum is at least target, or 0 if no subarray "
         "qualifies."
     ),
     "test_cases": [
         _case({"target": 7, "nums": [2, 3, 1, 2, 4, 3]}, 2),
         _case({"target": 4, "nums": [1, 4, 4]}, 1),
         _case({"target": 11, "nums": [1, 1, 1, 1, 1, 1, 1, 1]}, 0),
     ]},

    # ------------------------------------------------------- Stacks & Queues
    {"node": "Stacks & Queues", "title": "Valid Parentheses", "difficulty": "Easy",
     "description": (
         "Given a string s made only of the characters ( ) { } [ ], return true if every bracket is "
         "closed by a bracket of the same type, and in the correct order; otherwise false."
     ),
     "test_cases": [
         _case({"s": "()"}, True),
         _case({"s": "()[]{}"}, True),
         _case({"s": "(]"}, False),
         _case({"s": "([])"}, True),
         _case({"s": "([)]"}, False),
     ]},
    {"node": "Stacks & Queues", "title": "Daily Temperatures", "difficulty": "Medium",
     "description": (
         "Given an array temperatures of daily temperatures, return an array answer where answer[i] "
         "is the number of days you must wait after day i to reach a warmer temperature. If no "
         "warmer day ever comes, answer[i] is 0."
     ),
     "test_cases": [
         _case({"temperatures": [73, 74, 75, 71, 69, 72, 76, 73]}, [1, 1, 4, 2, 1, 1, 0, 0]),
         _case({"temperatures": [30, 40, 50, 60]}, [1, 1, 1, 0]),
         _case({"temperatures": [30, 60, 90]}, [1, 1, 0]),
     ]},

    # ---------------------------------------------------------- Linked Lists
    {"node": "Linked Lists", "title": "Reverse Linked List", "difficulty": "Easy",
     "description": (
         "Given the head of a singly linked list, reverse the list and return the new head. "
         "(Lists are written as arrays of node values, in order.)"
     ),
     "test_cases": [
         _case({"head": [1, 2, 3, 4, 5]}, [5, 4, 3, 2, 1]),
         _case({"head": [1, 2]}, [2, 1]),
         _case({"head": []}, []),
     ]},
    {"node": "Linked Lists", "title": "Merge Two Sorted Lists", "difficulty": "Easy",
     "description": (
         "Given the heads of two sorted singly linked lists, splice their nodes together into one "
         "sorted list and return its head. (Lists are written as arrays of node values, in order.)"
     ),
     "test_cases": [
         _case({"list1": [1, 2, 4], "list2": [1, 3, 4]}, [1, 1, 2, 3, 4, 4]),
         _case({"list1": [], "list2": []}, []),
         _case({"list1": [], "list2": [0]}, [0]),
     ]},
    {"node": "Linked Lists", "title": "Linked List Cycle", "difficulty": "Easy",
     "description": (
         "Given the head of a singly linked list, return true if the list contains a cycle (some node "
         "can be reached again by following next pointers), otherwise false. In the test input, pos "
         "is the index of the node the tail links back to, or -1 if the tail links to nothing; pos "
         "is only used to build the list and is not an argument of your function."
     ),
     "test_cases": [
         _case({"head": [3, 2, 0, -4], "pos": 1}, True),
         _case({"head": [1, 2], "pos": 0}, True),
         _case({"head": [1], "pos": -1}, False),
     ]},

    # ------------------------------------------------------------- Recursion
    {"node": "Recursion", "title": "Fibonacci Number", "difficulty": "Easy",
     "description": (
         "The Fibonacci numbers start F(0) = 0, F(1) = 1, and every later value is "
         "F(n) = F(n-1) + F(n-2). Given n, return F(n)."
     ),
     "test_cases": [
         _case({"n": 2}, 1),
         _case({"n": 3}, 2),
         _case({"n": 4}, 3),
     ]},
    {"node": "Recursion", "title": "Power of Two", "difficulty": "Easy",
     "description": (
         "Given an integer n, return true if n is a power of two (n = 2^k for some integer k >= 0), "
         "otherwise false."
     ),
     "test_cases": [
         _case({"n": 1}, True),
         _case({"n": 16}, True),
         _case({"n": 3}, False),
     ]},

    # ----------------------------------------------------------------- Trees
    {"node": "Trees", "title": "Maximum Depth of Binary Tree", "difficulty": "Easy",
     "description": (
         "Given the root of a binary tree, return its maximum depth: the number of nodes on the "
         "longest path from the root down to a leaf. (Trees are written level by level, with null "
         "for a missing child.)"
     ),
     "test_cases": [
         _case({"root": [3, 9, 20, None, None, 15, 7]}, 3),
         _case({"root": [1, None, 2]}, 2),
     ]},
    {"node": "Trees", "title": "Invert Binary Tree", "difficulty": "Easy",
     "description": (
         "Given the root of a binary tree, mirror it (swap the left and right child of every node) "
         "and return the root. (Trees are written level by level, with null for a missing child.)"
     ),
     "test_cases": [
         _case({"root": [4, 2, 7, 1, 3, 6, 9]}, [4, 7, 2, 9, 6, 3, 1]),
         _case({"root": [2, 1, 3]}, [2, 3, 1]),
         _case({"root": []}, []),
     ]},

    # --------------------------------------------------- Binary Search Trees
    {"node": "Binary Search Trees", "title": "Validate Binary Search Tree", "difficulty": "Medium",
     "description": (
         "Given the root of a binary tree, return true if it is a valid binary search tree: for every "
         "node, all values in its left subtree are strictly smaller and all values in its right "
         "subtree are strictly larger, and both subtrees are valid too. (Trees are written level by "
         "level, with null for a missing child.)"
     ),
     "test_cases": [
         _case({"root": [2, 1, 3]}, True),
         _case({"root": [5, 1, 4, None, None, 3, 6]}, False),
     ]},
    {"node": "Binary Search Trees", "title": "Kth Smallest Element in a BST", "difficulty": "Medium",
     "description": (
         "Given the root of a binary search tree and an integer k, return the k-th smallest value "
         "(counting from 1) among all node values. (Trees are written level by level, with null for "
         "a missing child.)"
     ),
     "test_cases": [
         _case({"root": [3, 1, 4, None, 2], "k": 1}, 1),
         _case({"root": [5, 3, 6, 2, 4, None, None, 1], "k": 3}, 3),
     ]},

    # ----------------------------------------------------------------- Heaps
    {"node": "Heaps", "title": "Kth Largest Element in an Array", "difficulty": "Medium",
     "description": (
         "Given an integer array nums and an integer k, return the k-th largest element in sorted "
         "order (duplicates count separately, so it is not the k-th distinct value)."
     ),
     "test_cases": [
         _case({"nums": [3, 2, 1, 5, 6, 4], "k": 2}, 5),
         _case({"nums": [3, 2, 3, 1, 2, 4, 5, 5, 6], "k": 4}, 4),
     ]},
    {"node": "Heaps", "title": "Last Stone Weight", "difficulty": "Easy",
     "description": (
         "You have a collection of stones with the given weights. Each turn, take the two heaviest "
         "stones and smash them together: if they weigh the same both are destroyed; otherwise the "
         "lighter is destroyed and the heavier is left with the difference in weight. Repeat until at "
         "most one stone remains, and return its weight (0 if none remain)."
     ),
     "test_cases": [
         _case({"stones": [2, 7, 4, 1, 8, 1]}, 1),
         _case({"stones": [1]}, 1),
     ]},

    # ---------------------------------------------------------------- Graphs
    {"node": "Graphs", "title": "Number of Islands", "difficulty": "Medium",
     "description": (
         "Given a 2D grid of '1' (land) and '0' (water), return the number of islands. An island is "
         "a group of land cells connected horizontally or vertically; everything outside the grid "
         "counts as water."
     ),
     "test_cases": [
         _case({"grid": [["1", "1", "1", "1", "0"],
                         ["1", "1", "0", "1", "0"],
                         ["1", "1", "0", "0", "0"],
                         ["0", "0", "0", "0", "0"]]}, 1),
         _case({"grid": [["1", "1", "0", "0", "0"],
                         ["1", "1", "0", "0", "0"],
                         ["0", "0", "1", "0", "0"],
                         ["0", "0", "0", "1", "1"]]}, 3),
     ]},
    {"node": "Graphs", "title": "Find if Path Exists in Graph", "difficulty": "Easy",
     "description": (
         "There are n vertices numbered 0 to n-1 and a list of bidirectional edges [u, v]. Return "
         "true if there is a path from vertex source to vertex destination, otherwise false."
     ),
     "test_cases": [
         _case({"n": 3, "edges": [[0, 1], [1, 2], [2, 0]], "source": 0, "destination": 2}, True),
         _case({"n": 6, "edges": [[0, 1], [0, 2], [3, 5], [5, 4], [4, 3]], "source": 0, "destination": 5}, False),
     ]},

    # ---------------------------------------------------- Dynamic Programming
    {"node": "Dynamic Programming", "title": "Climbing Stairs", "difficulty": "Easy",
     "description": (
         "You are climbing a staircase with n steps. Each move climbs either 1 or 2 steps. Return "
         "the number of distinct sequences of moves that reach the top."
     ),
     "test_cases": [
         _case({"n": 2}, 2),
         _case({"n": 3}, 3),
     ]},
    {"node": "Dynamic Programming", "title": "House Robber", "difficulty": "Medium",
     "description": (
         "nums[i] is the money in house i along a street. You cannot rob two adjacent houses. Return "
         "the maximum total you can rob."
     ),
     "test_cases": [
         _case({"nums": [1, 2, 3, 1]}, 4),
         _case({"nums": [2, 7, 9, 3, 1]}, 12),
     ]},
]
