"""
Builds the reviewed base roadmaps in data/base_roadmaps/<slug>.json (served by cached mode, see
app/pipeline/base_roadmaps.py). DRY RUN BY DEFAULT: prints the plan and makes no calls and writes nothing.

    PYTHONPATH=. python scripts/build_base_roadmaps.py --paths "Cybersecurity,DevOps"          # dry run
    PYTHONPATH=. python scripts/build_base_roadmaps.py --paths "Cybersecurity" --run           # real build
    PYTHONPATH=. python scripts/build_base_roadmaps.py --all --run                              # every path
    ... --run --force                  # rebuild paths whose file already exists and is valid
    ... --review-only                  # only rewrite docs/BASE_ROADMAP_REVIEW.md from the existing files

Each path is generated by the existing generate_roadmap with a NEUTRAL profile (no personal signals), then its
videos and resources are attached by the KB-only resolver (no network, zero fallback searches), then the result
is validated (phased shape, contiguous global_step_index, topic_refs inside the inventory, no duplicate titles,
videos/resources on every step) and written atomically. Resumable: a path whose file exists and is valid is
skipped (a rebuild needs --force); an existing file that is invalid counts as missing and is rebuilt. A failure
on one path does not stop the others (exit code 1 at the end).

Provider and model come from the environment: variables set BEFORE the command win over .env (python-dotenv
never overrides a variable that is already set), e.g. in PowerShell
    $env:LLM_PROVIDER="openai_compat"; $env:LLM_BASE_URL="https://integrate.api.nvidia.com/v1"
    $env:ROADMAP_MODEL_ID="openai/gpt-oss-20b"; $env:FAST_MODEL_ID="openai/gpt-oss-20b"; $env:FALLBACK_MODEL_ID="openai/gpt-oss-20b"
The provider host and models are printed (never a key) before anything else happens. Failover to another provider
is switched off for the run, so a failing provider fails the path instead of silently using a second one.
"""
import argparse
import json
import logging
import os
import sys
import time
from datetime import datetime, timezone
from pathlib import Path
from unittest.mock import patch
from urllib.parse import urlparse

from dotenv import load_dotenv
load_dotenv()   # does not override variables already present in the environment: those win

from app.config import Config
from app.pipeline import base_roadmaps, llm_client
from app.pipeline import roadmap_generator as rg
from app.pipeline.career_path_registry import CAREER_PATHS
from app.pipeline.rag import load_index
from app.pipeline.roadmap_generator import generate_roadmap
from app.pipeline.youtube_resources import fetch_resources_for_roadmap

INDEX_PATH = "data/processed/faiss_index"
DEFAULT_DOCS_FILE = Path("docs") / "BASE_ROADMAP_REVIEW.md"
NEUTRAL_SIGNALS = {}    # no goal / avoid / target_company / notes: the same roadmap for every student


def provider_description():
    """Lines that say which provider, host and models this run uses. Never a key (only the variable's NAME)."""
    provider = Config.LLM_PROVIDER
    lines = [f"provider: {provider}"]
    if provider == "openai_compat":
        host = urlparse(Config.LLM_BASE_URL).hostname or "?"
        variable = llm_client._openai_key_variable()
        lines.append(f"host: {host}")
        lines.append(f"key variable: {variable} ({'set' if getattr(Config, variable, '') else 'NOT SET'})")
    elif provider == "bedrock":
        lines.append(f"region: {Config.AWS_REGION or '(not set)'}")
    else:
        lines.append("host: Gemini API (SDK)")
    lines.append(f"models: roadmap={Config.ROADMAP_MODEL_ID or '(default)'} fast={Config.FAST_MODEL_ID or '(default)'} "
                 f"fallback={Config.FALLBACK_MODEL_ID or '(none)'}")
    lines.append(f"phase concurrency: {Config.PHASE_CONCURRENCY}   reasoning effort: {Config.LLM_REASONING_EFFORT or '(empty)'}")
    return lines


def disable_failover():
    """Blank the OTHER providers' credentials in this process so llm_client cannot fail over to them (and no YouTube)."""
    others = {"gemini": ("AWS_BEARER_TOKEN_BEDROCK", "AWS_ACCESS_KEY_ID"), "bedrock": ("GEMINI_API_KEY",)}.get(
        Config.LLM_PROVIDER, ("GEMINI_API_KEY", "AWS_BEARER_TOKEN_BEDROCK", "AWS_ACCESS_KEY_ID"))
    for name in others + ("YOUTUBE_API_KEY",):
        os.environ[name] = ""


def file_status(path, chunks, out_dir):
    """('missing' | 'valid' | 'stale' | 'invalid', detail) for a path's current file."""
    target = base_roadmaps.path_for(path, out_dir)
    if not target.is_file():
        return "missing", ""
    try:
        document = json.loads(target.read_text(encoding="utf-8"))
        problems, stale = base_roadmaps.validate_document(document, path, chunks)
    except Exception as exc:
        return "invalid", type(exc).__name__
    if problems:
        return "invalid", problems[0]
    return ("stale" if stale else "valid"), ""


def plan_action(status, force):
    if status == "missing":
        return "build"
    if status == "invalid":
        return "rebuild (existing file is invalid)"
    return "rebuild (--force)" if force else "skip (exists; --force to rebuild)"


class _Counters(logging.Handler):
    """Counts the generator's duplicate warnings: a rewrite of a repeating phase, and a repeat kept after its rewrite."""
    def __init__(self):
        super().__init__(logging.WARNING)
        self.rewritten = self.kept = 0

    def emit(self, record):
        message = record.getMessage()
        if message.startswith("Kept a step in phase"):
            self.kept += 1
        elif " repeats " in message and "rewriting this phase once" in message:
            self.rewritten += 1


def build_path(path, index, chunks, out_dir):
    """Builds, validates and writes one path. Returns a summary row. Raises on failure (the caller isolates it)."""
    started = time.perf_counter()
    counters = _Counters()
    logger = logging.getLogger(rg.__name__)
    discarded = {"n": 0}
    real_validate = rg._validate_topic_refs

    def counting_validate(steps, valid_node_ids):
        before = sum(len(s.get("topic_refs") or []) for s in steps)
        result = real_validate(steps, valid_node_ids)
        discarded["n"] += before - sum(len(s.get("topic_refs") or []) for s in result)
        return result

    logger.addHandler(counters)
    try:
        with patch.object(rg, "_validate_topic_refs", counting_validate):
            roadmap, audit = generate_roadmap(path, NEUTRAL_SIGNALS, index, chunks)
    finally:
        logger.removeHandler(counters)
    roadmap, _stats = fetch_resources_for_roadmap(roadmap, chunks=chunks, max_fallback_searches=0, use_youtube=False)
    settings = {"profile": "neutral", "provider": Config.LLM_PROVIDER,
                "llm_host": urlparse(Config.LLM_BASE_URL).hostname if Config.LLM_PROVIDER == "openai_compat" else None,
                "phase_concurrency": Config.PHASE_CONCURRENCY,
                "duplicate_similarity_threshold": Config.DUPLICATE_SIMILARITY_THRESHOLD,
                "reasoning_effort": Config.LLM_REASONING_EFFORT or "", "resources": "kb_only"}
    document = base_roadmaps.build_document(path, roadmap, audit, chunks, Config.ROADMAP_MODEL_ID or "(default)", settings,
                                            datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"))
    problems, _ = base_roadmaps.validate_document(document, path, chunks)
    if problems:
        raise ValueError(f"validation failed: {problems[0]} (+{len(problems) - 1} more)")
    base_roadmaps.write_atomic(base_roadmaps.path_for(path, out_dir), document)
    return {"path": path, "status": "built", "phases": len(roadmap["phases"]),
            "steps": sum(len(p["steps"]) for p in roadmap["phases"]), "discarded_refs": discarded["n"],
            "dups_rewritten": counters.rewritten, "dups_kept": counters.kept,
            "seconds": round(time.perf_counter() - started, 1), "model": document["metadata"]["model_id"]}


def _one_line(text, limit=160):
    return " ".join(str(text).split())[:limit]


def write_review(out_dir, docs_file, chunks):
    """docs/BASE_ROADMAP_REVIEW.md: every valid base file's phases, all step titles and the first two step
    descriptions of each phase, for review by eye. Paths without a valid file are listed as not built."""
    lines = ["# Base roadmap review", "",
             "Generated by `scripts/build_base_roadmaps.py`; rewritten on every `--run` and by `--review-only`. "
             "For each career path: every phase, every step title, and the descriptions of the first two steps of each phase. "
             "Read these before committing the files in `data/base_roadmaps/`.", ""]
    for path in CAREER_PATHS:
        status, detail = file_status(path, chunks, out_dir)
        lines.append(f"## {path}")
        if status in ("missing", "invalid"):
            lines += ["", f"_Not built yet_{' (file invalid: ' + _one_line(detail) + ')' if status == 'invalid' else ''}.", ""]
            continue
        document = json.loads(base_roadmaps.path_for(path, out_dir).read_text(encoding="utf-8"))
        meta, roadmap = document["metadata"], document["roadmap"]
        total = sum(len(p["steps"]) for p in roadmap["phases"])
        lines += ["", f"Model `{meta['model_id']}`, built {meta['built_at']}, {len(roadmap['phases'])} phases, {total} steps"
                  + (" - **STALE: the knowledge base changed since this was built**" if status == "stale" else "") + ".", ""]
        for phase in roadmap["phases"]:
            lines += [f"### Phase {phase['phase_number']}: {phase['title']} ({len(phase['steps'])} steps)", ""]
            lines += [f"{s['global_step_index']}. {s['title']}" for s in phase["steps"]]
            lines.append("")
            for s in phase["steps"][:2]:
                lines += [f"> **{s['title']}**: {_one_line(s['description'], 600)}", ""]
    Path(docs_file).parent.mkdir(parents=True, exist_ok=True)
    Path(docs_file).write_text("\n".join(lines) + "\n", encoding="utf-8")


def print_table(rows):
    header = ("path", "result", "phases", "steps", "discarded_refs", "dups(rewritten/kept)", "seconds", "model")
    body = [(r["path"], r["status"], r.get("phases", ""), r.get("steps", ""), r.get("discarded_refs", ""),
             f"{r['dups_rewritten']}/{r['dups_kept']}" if "dups_rewritten" in r else "", r.get("seconds", ""), r.get("model", ""))
            for r in rows]
    widths = [max(len(str(x)) for x in col) for col in zip(header, *body)]
    for line in [header] + body:
        print("  ".join(str(x).ljust(w) for x, w in zip(line, widths)).rstrip())


def parse_args(argv):
    parser = argparse.ArgumentParser(description="Build the reviewed base roadmaps (dry run unless --run).")
    which = parser.add_mutually_exclusive_group()
    which.add_argument("--paths", help='comma-separated career paths, e.g. "Cybersecurity,DevOps"')
    which.add_argument("--all", action="store_true", help="every career path")
    parser.add_argument("--run", action="store_true", help="really build (calls the configured LLM); without it nothing is called or written")
    parser.add_argument("--force", action="store_true", help="rebuild paths whose file already exists and is valid")
    parser.add_argument("--review-only", action="store_true", help="only rewrite the review document from the existing files")
    parser.add_argument("--out-dir", default=str(base_roadmaps.BASE_DIR), help=argparse.SUPPRESS)
    parser.add_argument("--docs-file", default=str(DEFAULT_DOCS_FILE), help=argparse.SUPPRESS)
    return parser, parser.parse_args(argv)


def main(argv=None):
    parser, args = parse_args(argv)
    if not (args.paths or args.all or args.review_only):
        parser.error("give --paths \"A,B\" or --all (add --run to build)")
    for line in provider_description():
        print(line)
    index, chunks = load_index(INDEX_PATH)
    if args.review_only:
        write_review(args.out_dir, args.docs_file, chunks)
        print(f"wrote {args.docs_file}")
        return 0
    paths = list(CAREER_PATHS) if args.all else [p.strip() for p in args.paths.split(",") if p.strip()]
    unknown = [p for p in paths if p not in CAREER_PATHS]
    if unknown:
        print(f"unknown career path(s): {unknown}. Valid: {CAREER_PATHS}")
        return 2

    plan = []
    print(f"\n{'RUN' if args.run else 'DRY RUN (no calls, nothing written; add --run to build)'}  out-dir: {args.out_dir}\n")
    for path in paths:
        status, detail = file_status(path, chunks, args.out_dir)
        action = plan_action(status, args.force)
        inventory = len(rg._dedup_inventory(rg._topic_inventory(path, chunks)))
        plan.append((path, action))
        print(f"- {path}: file {status}{' (' + _one_line(detail, 80) + ')' if detail else ''}; {inventory} topics; {action}"
              f"{'; up to ' + str(rg.MAX_PHASES + 1) + ' LLM requests plus retries' if action.startswith(('build', 'rebuild')) else ''}")
    if not args.run:
        return 0

    disable_failover()
    print("\nfailover to another provider: disabled for this run\n")
    rows = []
    for path, action in plan:
        if action.startswith("skip"):
            rows.append({"path": path, "status": "skipped"})
            continue
        print(f"building {path} ...", flush=True)
        try:
            row = build_path(path, index, chunks, args.out_dir)
        except Exception as exc:    # one path failing must not stop the others
            row = {"path": path, "status": f"FAILED {type(exc).__name__}: {_one_line(exc, 100)}"}
        print(f"  -> {row['status']}", flush=True)
        rows.append(row)
    write_review(args.out_dir, args.docs_file, chunks)
    print()
    print_table(rows)
    print(f"\nreview document: {args.docs_file}")
    return 1 if any(r["status"].startswith("FAILED") for r in rows) else 0


if __name__ == "__main__":
    sys.exit(main())
